id: P12826F29
initial_creation_type: ocr
source_metadata:
  volumes:
    6d3bf1667ea74304a54a7a9465cff5e8:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ཕྱག་ན་རྡོ་རྗེ་གཏུམ་པོ་ཆེན་པོ་ཁྲོས་པ་ཞེས་བྱ་བའི་སྒྲུབ་ཐབས།
      total_pages: 1464
      volume_number: 47
